= Java 8+ words substitution functions for building fluent api

image:https://github.com/stawirej/fluent-api/workflows/Java%20CI%20with%20Maven/badge.svg[Java CI with Maven]
image:http://img.shields.io/:license-apache-blue.svg[License,link=http://www.apache.org/licenses/LICENSE-2.0.html]

= Practical application of higher-order functions and function currying for building fluent api in Java

== Executive summary

== Introduction

=== Situation

When we create library or framework we expose methods with set of parameters as a public API.
For methods with a small amount of parameters we might not have an issue with that.
Especially when we provide decent documentation.
We use them and experience shows we get used to their look.

=== Complication

We struggle to introduce fluent api approach.
It might rise some challenge for new or existing code.
For covering trivial functionality connected with creating objects we always can use a builder pattern.
We start to struggle when comes to create fluent api of more complicated behavior.

---

[quote,Grady Booch author of Object Oriented Analysis and Design with Applications]
____
Clean code is simple and direct.
Clean code reads like well-written prose. +
Clean code never obscures the designer’s intent but rather is full of crisp abstractions and straightforward lines of control.
____

---

Stop for a moment and try to think about part of above quote: "… well-written prose." Often we encounter methods like:

[source,java]
----
library.lend(book, reader);
----

Due to decent naming we clearly see this code realize book lending functionality.
However, try to read that code at loud.
You will get something like: "Library lend book reader".
Doesn't sound as "well-written prose"?
It doesn't even sound as a proper sentence.

=== Key question

How can we easily build a fluent API in Java and mimic natural language?

== Answer

=== Missing parts of speech

Terry Bozzio was asked once why he need such a big drum kit.
"To play music, I need notes!" he said.
Paraphrasing: "To create fluent API, we need words!"

We know a concept of having class names (things) as nouns and verbs for methods (behaviours).
It worked pretty well so far.
However, we face an obstacle when we try to build fluent API with limited parts of speech.

To solve it, we need to introduce missing part of english sentences as e.g. prepositions.
Having all verbs, nouns and prepositions in place we can build API which sounds like "well-written prose".

Let's add preposition to our example.

[source,java]
----
library.lend(book).to(reader);
----

Now we have correct english sentence: "Library lend book to reader"!

To introduce this concept into Java code in practical way we need to use higher-order functions and function currying.

=== Higher-order functions

=== Function currying

In mathematics and computer science, currying is the technique of translating the evaluation of a function that +
takes multiple arguments into evaluating a sequence of functions, each with a single argument (https://en.wikipedia.org/wiki/Currying[wiki]).
We would like to apply this technique.
Having one-argument functions and "curry" them enable creating fluent api.

=== Decorator

== Appendix

DSL not supporting lambdas when not a functional interface (interface with one function).

=== Maven Central
